language: go
go:
  - 1.4
sudo: false
install:
  - go get github.com/spf13/hugo
  - gem install bundler
  - bundle install --without development --deployment --jobs=3 --retry=3 --binstubs
cache:
  directories:
  - vendor/bundle
script:
 - bin/compass compile -e production --force
 - hugo
 - bundle exec htmlproof public
after_script:
  - _bin/deploy.sh
branches:
  only:
  - master
env:
  global:
    - RESET=true
    - GH_REF=github.com/pickleshb/Website.git
    - secure: "vyCvs3BUjpQQfSQsqkStdYHsXXAHfcXRuGfZOZwaZ7iYDo76bHw1FhG026fNC8aOoB0PfTOMgIJ5QUZIMdKT55DQapx1IOc3+ImpzqkXqF9aWxt53EuDxXcfg00lcevDSuxTNRNWSVgljxZ5EdsFguPvqBjvvOFGiUhDTj7FWtIx925ogwClC/ZC/X+sfupb3mzGg4Inz1pFAIUUrQOflrCIxEeSUoge5D/L1oihKjESXyw61f30q4IjYYsOyy8OFm4QELrrnddhe5B+Fw7uhMJoBlLhQs389WGOLtNZ6rnwAS3i/W8D1bYXn3uoJT+rA/LpxEkObeu1387ayFa+UuAu+oQR6yIh4Sh/SBwEkPtLE9gacpnIZuBOsML8bFpYbORvVksrj7kFbAnR53cUKTXB3TbXPuDZ+V5CU1u+n9tL9cMmT9apOau4USU4DlI+pGqXw2JorbN4qb3YCTGVJaxNtCAfyylUedf0KLtJG0rUEKxiMRTNtcI2XMQRAa/RxHv38U7DhXMM/NuxmdD3gvSZYh7b9B8tBw1w92wTpuqL1ZUESwEPQcNIvgb7REovQ4nXpMwjF6PJ2xk7Q2HTq3ktgjafQ0PX+T7A4usYudMygG8V13yu8BHXKgcWJAjS8qi7XsgGKyL5QOt1oXpSgeyS1O136qpOibHD/XjUJtE="
